workflows:
  ios-demo:
    name: iOS Shorebird Demo
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - shorebird_credentials # Recuerda crear este grupo con la variable SHOREBIRD_TOKEN
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Shorebird
        script: |
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh | bash
      
      - name: Flutter Dependencies
        script: |
          flutter pub get

      - name: Pod Install
        script: |
          find . -name "Podfile" -exec dir "{}" \;
          cd ios
          pod install
          cd ..

      - name: Shorebird Release iOS
        script: |
          # Genera la build release usando Shorebird
          # Requiere que SHOREBIRD_TOKEN esté configurado en Codemagic
          shorebird release ios --artifact-type ipa
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcode_derived_data/**/*.app
      - *.dSYM.zip
    publishing:
      email:
        recipients:
          - user@example.com # Cambia esto por tu email
