// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe693GgtjmZ9mxR-eCBSNquyQ4YWVNUfM',
    appId: '1:20865995402:web:f2ba17da083352c4409373',
    messagingSenderId: '20865995402',
    projectId: 'golden-xi-25e9b',
    authDomain: 'golden-xi-25e9b.firebaseapp.com',
    storageBucket: 'golden-xi-25e9b.firebasestorage.app',
    measurementId: 'G-KJZLH9SECG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk1zoO92tRgSdCot1F8hxJHax-a0iXBZQ',
    appId: '1:20865995402:android:9816d16009e8b101409373',
    messagingSenderId: '20865995402',
    projectId: 'golden-xi-25e9b',
    storageBucket: 'golden-xi-25e9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0nOtYV8evXyJlU6oPY3JFehoqV8_GDnI',
    appId: '1:20865995402:ios:28f5c5b367b5d349409373',
    messagingSenderId: '20865995402',
    projectId: 'golden-xi-25e9b',
    storageBucket: 'golden-xi-25e9b.firebasestorage.app',
    iosBundleId: 'com.antoniojabang.goldenxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB6OnnfuitFnaYWu4BvtGKaoLFk4cm-GE',
    appId: '1:20865995402:ios:729749b1bf49ee9a3e3e9b',
    messagingSenderId: '20865995402',
    projectId: 'golden-xi-25e9b',
    storageBucket: 'golden-xi-25e9b.firebasestorage.app',
    iosBundleId: 'com.antoniojabang.goldenxi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB6OnnfuitFnaYWu4BvtGKaoLFk4cm-GE',
    appId: '1:20865995402:windows:ee9a3e3e9b46e523dc2441',
    messagingSenderId: '20865995402',
    projectId: 'golden-xi-25e9b',
    authDomain: 'golden-xi-25e9b.firebaseapp.com',
    storageBucket: 'golden-xi-25e9b.firebasestorage.app',
    measurementId: 'G-KJZLH9SECG',
  );
}
